; Girls Frontline Assistant Rainmeter
; Version 10.0
; Creative Commons BY-NC-SA 3.0

[Variables]
;----------------------------------------------
; DOLL DATABASE [ HG CODE ]
;----------------------------------------------
hg1 = 212
hg2 = 096
hg3 = 114
hg4 = 142
hg5 = 183
hg6 = 
hg7 = 
hg8 = 
hg9 = 
hg10 = 
hg11 = 
hg12 = 
hg13 = 
hg14 = 
hg15 = 

;----------------------------------------------
; DOLL DATABASE [ HG NAME ]
;----------------------------------------------
hg1n = K5
hg2n = Grizzly
hg3n = Welrod MkII
hg4n = Five-seveN
hg5n = Ceonteder
hg6n = 
hg7n = 
hg8n = 
hg9n = 
hg10n = 
hg11n = 
hg12n = 
hg13n = 
hg14n = 
hg15n = 

;----------------------------------------------
; DOLL DATABASE [ RF CODE ]
;----------------------------------------------
rf1 = 044
rf2 = 174
rf3 = 036
rf4 = 039
rf5 = 046
rf6 = 048
rf7 = 148
rf8 = 179
rf9 = 192
rf10 = 
rf11 = 
rf12 = 
rf13 = 
rf14 = 
rf15 = 

;----------------------------------------------
; DOLL DATABASE [ RF NAME ]
;----------------------------------------------
rf1n = SV-98
rf2n = Type81R
rf3n = Springfield
rf4n = Mosin-Nagant
rf5n = Kar98K
rf6n = WA2000
rf7n = IWS2000
rf8n = Gd DSR-50
rf9n = JS-05
rf10n = 
rf11n = 
rf12n = 
rf13n = 
rf14n = 
rf15n = 

;----------------------------------------------
; DOLL DATABASE [ SMG CODE ]
;----------------------------------------------
smg1 = 093
smg2 = 176
smg3 = 101
smg4 = 103
smg5 = 016
smg6 = 020
smg7 = 115
smg8 = 127
smg9 = 135
smg10 = 143
smg11 = 228
smg12 = 
smg13 = 
smg14 = 
smg15 = 

;----------------------------------------------
; DOLL DATABASE [ SMG NAME ]
;----------------------------------------------
smg1n = IDW
smg2n = TMP
smg3n = UMP9
smg4n = UMP45
smg5n = Thompson
smg6n = Vector
smg7n = Suomi
smg8n = Type 79
smg9n = SR-3MP
smg10n = RO635
smg11n = 100 Shiki
smg12n = 
smg13n = 
smg14n = 
smg15n = 

;----------------------------------------------
; DOLL DATABASE [ AR CODE ]
;----------------------------------------------
ar1 = 054
ar2 = 055
ar3 = 056
ar4 = 057
ar5 = 118
ar6 = 062
ar7 = 065
ar8 = 122
ar9 = 129
ar10 = 172
ar11 = 
ar12 = 
ar13 = 
ar14 = 
ar15 =  

;----------------------------------------------
; DOLL DATABASE [ AR NAME ]
;----------------------------------------------
ar1n = M16
ar2n = M4A1
ar3n = M4 SOPMOD II
ar4n = ST AR-15
ar5n = 9A-91
ar6n = G41
ar7n = HK416
ar8n = Gr G11
ar9n = Type95
ar10n = Am RFB
ar11n = 
ar12n = 
ar13n = 
ar14n = 
ar15n = 

;----------------------------------------------
; DOLL DATABASE [ SG CODE ]
;----------------------------------------------
sg1 = 155
sg2 = 165
sg3 = 157
sg4 = 188
sg5 = 
sg6 = 
sg7 = 
sg8 = 
sg9 = 
sg10 = 
sg11 = 
sg12 = 
sg13 = 
sg14 = 
sg15 = 

;----------------------------------------------
; DOLL DATABASE [ SG NAME ]
;----------------------------------------------
sg1n = M590
sg2n = M1014
sg3n = KSG
sg4n = S.A.T.8
sg5n = 
sg6n = 
sg7n = 
sg8n = 
sg9n = 
sg10n = 
sg11n = 
sg12n = 
sg13n = 
sg14n = 
sg15n = 

;----------------------------------------------
; DOLL DATABASE [ MG CODE ]
;----------------------------------------------
mg1 = 088
mg2 = 121
mg3 = 112
mg4 = 
mg5 = 
mg6 = 
mg7 = 
mg8 = 
mg9 = 
mg10 = 
mg11 = 
mg12 = 
mg13 = 
mg14 = 
mg15 = 

;----------------------------------------------
; DOLL DATABASE [ MG NAME ]
;----------------------------------------------
mg1n = MG3
mg2n = Mk48
mg3n = Negev
mg4n = 
mg5n = 
mg6n = 
mg7n = 
mg8n = 
mg9n = 
mg10n = 
mg11n = 
mg12n = 
mg13n = 
mg14n = 
mg15n = 