; Girls Frontline Assistant Rainmeter
; Version 10.0
; Creative Commons BY-NC-SA 3.0

[Variables]
;----------------------------------------------
; MENU BUTTON POSITION VARIABLES
;----------------------------------------------
ui1-pos-x = 35
ui2-pos-x = 72
ui3-pos-x = 109
ui4-pos-x = 146
ui5-pos-x = 183
ui6-pos-x = 220
ui-pos-y = 57

;----------------------------------------------
; COMPUTER LOGO POSITION VARIABLES
;----------------------------------------------
pc_logo1-x = 41
pc_logo2-x = 84
pc_logo3-x = 127
pc_logo4-x = 170
pc_logo5-x = 213
pc_logo-y = 260

;----------------------------------------------
; COMPUTER STATUS POSITION VARIABLES
;----------------------------------------------
pc_text1-x = 57
pc_text2-x = 100
pc_text3-x = 143
pc_text4-x = 186
pc_text5-x = 229
pc_text-y = 297

;----------------------------------------------
; COLOR CHANGER POSITION VARIABLES
;----------------------------------------------
clr_pos1-x = 43
clr_pos2-x = 83
clr_pos3-x = 123
clr_pos4-x = 163
clr_pos5-x = 203
clr_pos-y = 98
clr_input-x = 43
clr_input-y = 133

;----------------------------------------------
; TEMPORARY MOVE FOR HOME STATUS
;----------------------------------------------
home_ui_pos =0

;----------------------------------------------
; T-DOLL CLASSES POSITION VARIABLES
;----------------------------------------------
doll_m_pos_x1 = 39
doll_m_pos_x2 = 93
doll_m_pos_x3 = 147
doll_m_pos_x4 = 201
doll_m_pos_y1 = 93
doll_m_pos_y2 = 133

;----------------------------------------------
; T-DOLL CHARACTER POSITION VARIABLES
;----------------------------------------------
a-pos-x1 = 39
a-pos-x2 = 111
a-pos-x3 = 183
a-pos-y1 = 182
a-pos-y2 = 254
a-pos-y3 = 326
a-pos-y4 = 398
a-pos-y5 = 470
a-pos-y6 = 542
a-pos-y7 = 614

;----------------------------------------------
; TO DO LIST DISPLAY BUTTON POSITION VARIABLES
;----------------------------------------------
b1-pos-x = 35
b2-pos-x = 72
b3-pos-x = 109
b4-pos-x = 146
b5-pos-x = 183
b6-pos-x = 220
b-pos-y = 93

;----------------------------------------------
; CUSTOM POSITION VARIABLES
;----------------------------------------------
c1-pos-x = 35
c2-pos-x = 72
c3-pos-x = 109
c4-pos-x = 146
c5-pos-x = 183
c6-pos-x = 220
c-pos-y = 130

;----------------------------------------------
; SETTING MENU VARIABLES
;----------------------------------------------
d1-pos-x = 41
d2-pos-x = 84
d3-pos-x = 127
d4-pos-x = 170
d5-pos-x = 213
d-pos-y = 199
d-pos-y2 = 236

;----------------------------------------------
; TO DO LIST DISPLAY POSITION VARIABLES
;----------------------------------------------

e1-pos1-y = 65
e1-pos2-y = 69
e2-pos1-y = 100
e2-pos2-y = 104
e3-pos1-y = 135
e3-pos2-y = 139
e4-pos1-y = 170
e4-pos2-y = 174
e5-pos1-y = 205
e5-pos2-y = 209
e6-pos1-y = 240
e6-pos2-y = 244
e7-pos1-y = 275
e7-pos2-y = 279
e8-pos1-y = 310
e8-pos2-y = 314
e9-pos1-y = 345
e9-pos2-y = 349
e10-pos1-y = 380
e10-pos2-y = 384

;----------------------------------------------
; ADDITIONAL VARIABLES
;----------------------------------------------

